mysql_master: sekapictures-2
prometheus_host: sekapictures-3
dns_master: sekapictures-3
influx_host: sekapictures-3
mysql_database: agama
mysql_user: agama
mysql_exporter_user: exporter
mysql_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          66373136333362313933346432316361323165643238373462626333613966356362613832363062
          3433316166323461313532653264666437376532343863390a366332623232366337373832623766
          62653338663163643266323465333235333335376534646364646362626135613039613064376631
          3034616330613232300a336630663037393166393066306466343764326435313564393936623862
          3533

startup_name: gleppy.io

haproxy_port: 88

backup_server: 192.168.42.132

route:
 - 1.1.1.1;
 - 8.8.8.8;
 - 9.9.9.9;
 - 9.9.9.10;

corpnets:
 - 192.168.42.0/24;
 - 127.0.0.0/8;
 - 172.17.0.0/16;

db_name: db.gleppy

dns_serial: "{{ (hostvars['sekapictures-2']['ansible_date_time']['time']) | replace('-','') | replace(':','') }}"

dns_cname_records:
  grafana: "{{ groups['grafana'][0] }}"
  influxdb:  "{{ groups['influxdb'][0] }}"
  lb1: "{{ groups['haproxy'][0] }}"
  lb2: "{{ groups['haproxy'][1] }}"
  mysql1: "{{ groups['db_servers'][0] }}"
  mysql2: "{{ groups['db_servers'][1] }}"
  ns1: "{{ groups['dns_servers'][0] }}"
  ns2: "{{ groups['dns_servers'][1] }}"
  ns3: "{{ groups['dns_servers'][2] }}"
  prometheus: "{{ groups['prometheus'][0] }}"
  web1: "{{ groups['web_servers'][0] }}"
  web2: "{{ groups['web_servers'][1] }}"

dns_a_records:
  backup: "{{ backup_server }}"

mysql_exporter_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          34616637666533323265616539303266316231653936323661353434613665633139303235613961
          6461663535333265396234363261333335666135356330380a353435616361356436666438303362
          34633164636536613166626632303566653833643538386532376362303266303866373431336233
          3833323730323030300a386639393761313437663730313232613461616537323933653065373034
          62393063306631323861376631616437353139386239353163663161303836393338

backup_server_ssh_key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEu6pFFWyuRrl4WGFPQGElYN9txwTGm2wSntcpVAaN90

mysql_backup_user: backup

mysql_replication_user: replication

mysql_replication_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          36653234363439373566376530383038363434376166323266626166633737333832306239306332
          3266626338303364333132303832643237363865616236610a616130623763623636353062323739
          33393332316234623835333265336666646436303061656365656536623631626630366139363362
          3165626563336430630a306662336235386338613538353363613739323239343736363533616536
          6536

node_id: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'].split('.')[-1] }}"

grafana_admin_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          37656430653135396362366662646566306130346133613261666637393239303464316664663131
          3636313731336232383238376134343035353931653562330a343631653965333863313333393832
          34383465336234393930336432376138623031336637666562306261393935336466616437636234
          3130653464633532370a356663663434303864363532373131343338623434383466376563366262
          62336362313761316333313039316666313936306536613330303961373262333332

dns_update_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          66663632376637333562356263383432393138343937313661303433376664346263353530333837
          3532396433376265393065666430393737653565636663350a366231333735346564643137373037
          62643361386332643039303539376366613639396465623739646339616231386532343132353566
          3161323131633539320a316162376631623838663933346264366533393132333839323730636135
          38323137666230336236363961333437646433376231613130363861303430376663373137666363
          3837633561393532623934623363363065363066396636393836

dns_transfer_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63376636663337623334383137373262306239656133333662643432376332356565646530306135
          3430353332343363643462376132646464396136333139310a363439313765613231396437356138
          39666535363661613234653232376661316565626134663234303263613261646634313333656165
          6365303861323162300a376338623939653633613830353561356336656565646162646234386237
          36396565303733613261633131303035616335306438343134383233653266313936303736333030
          3536353936653866663763613532303065353737393362633638

grafana_port: 8180

# will be incrimented by 1, so result is agama_port + 1 
agama_port: 8000

# how many agama docker containers will be running 
agama_instances: 2

docker_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          31663432376163393165366431626138663839383034366565643234633234613862326263336564
          3766653638306534636463636538323133643738383834350a396230333939376539613661343966
          65336564303336303937633935306139656166633132313030663362666266393032313433366330
          3831666338393335370a393262626136363238653536353738383530623262343137613238373539
          3438
