mysql_host: sekapictures-2
influx_host: sekapictures-2
mysql_database: agama
mysql_user: agama
mysql_exporter_user: exporter
mysql_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          66373136333362313933346432316361323165643238373462626333613966356362613832363062
          3433316166323461313532653264666437376532343863390a366332623232366337373832623766
          62653338663163643266323465333235333335376534646364646362626135613039613064376631
          3034616330613232300a336630663037393166393066306466343764326435313564393936623862
          3533

startup_name: gleppy.io

backup_server: 192.168.42.156

route:
 - 1.1.1.1;
 - 8.8.8.8;
 - 9.9.9.9;
 - 9.9.9.10;

corpnets:
 - 192.168.42.0/24;
 - 127.0.0.0/8;

db_name: db.gleppy

mysql_exporter_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          65623032613065626434333561313066313033633037383838633362633630373238366337643638
          6464396431646564396633306534646432333862333863310a646531386332396132656233346564
          65616366386432663131313335643232383566636330633436646433646631313162663065326533
          3164326637323833340a656432613933303438316131616432616130336165376236393237633136
          39636138613933333130643835636438386630623262323637353633643166613765

backup_server_ssh_key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBSne71MCp6CQCHURWe3CLud6vPDkLfL83Oab/giAI7O

mysql_backup_user: backup

