apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    # Access mode - proxy (server in the UI) or direct (browser in the UI).
    access: proxy
    url: http://sekapictures-1:9090/prometheus
    editable: true

  - name: InfluxDB
    type: influxdb
    access: proxy
    database: latency
    url: http://sekapictures-2:8086

  - name: InfluxDB
    type: telegraf
    access: proxy
    database: telegraf
    url: http://sekapictures-2:8086
