- name: prometheus-nginx-exporter
  ansible.builtin.apt:
    name: prometheus-nginx-exporter
    state: latest
  

- name: Place Nginx config for nginx-exporter
  ansible.builtin.template:
    src: exporter.j2
    dest: /etc/nginx/sites-enabled/exporter
  notify: 
    #- Restart Nginx
    #- Restart Prometheus
    - Restart prometheus-nginx-exporter
  register: nginx_config

- name: Restart Nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
  when: nginx_config.changed

- name: Ensure nginx-exporter is started
  ansible.builtin.service:
    name: prometheus-nginx-exporter
    enabled: yes
    state: started