- name: Add grafana gpg key
  shell: curl https://packages.grafana.com/gpg.key | sudo apt-key add -

- name: Add grafana repo 
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present
    filename: grafana

- name: Install grafana
  apt: 
      name: grafana
      state: present
      update_cache: yes

- name: Enable and start grafana service
  service:
    name: grafana-server
    enabled: yes
    state: started

- name: Add grafana password
  shell: grafana-cli admin reset-admin-password "{{mysql_exporter_pass}}"

- name: Place prometheus datasource
  ansible.builtin.template:
    src: prometheus.yaml
    dest: /etc/grafana/provisioning/datasources/

- name: Place prometheus dashboard
  ansible.builtin.template:
    src: pdashboard.yaml
    dest: /etc/grafana/provisioning/dashboards/
    force: yes

- name: Place grafana configuration
  ansible.builtin.template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
    force: yes

- name: Place main.json 
  ansible.builtin.template:
    src: main.json
    dest: /var/lib/grafana/dashboards/
    force: yes

- name: Restart grafana service
  ansible.builtin.service:
    name: grafana-server
    state: restarted

- name: Restart prometheus-mysqld-exporter
  ansible.builtin.service:
    name: prometheus-mysqld-exporter
    state: restarted

- name: Restart mysql service
  ansible.builtin.service:
    name: mysql
    state: restarted

- name: Restart bind9 service
  ansible.builtin.service:
    name: bind9
    state: restarted